import "~/styles/globals.css";

import { type Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "~/components/ui/sidebar";
import { AppSidebar } from "~/components/app-sidebar";
import { TooltipProvider } from "~/components/ui/tooltip";

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const instrumentSans = Instrument_Sans({
    subsets: ["latin"],
    variable: "--font-instrument-sans",
    display: "swap",
});

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" className={`${instrumentSans.variable} dark`}>
            <body className="antialiased">
                <TooltipProvider>
                    <SidebarProvider>
                        <AppSidebar />
                        <main className="w-full">
                            {children}
                        </main>
                    </SidebarProvider>
                </TooltipProvider>
            </body>
        </html>
    );
}
